version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_HOST: db
      DB_USER: /run/secrets/DB_USER
      DB_NAME: /run/secrets/DB_NAME
    ports:
      - "8080:8080"
    secrets:
      - DB_PASSWORD
      - DB_USER
      - DB_NAME
secrets:
  DB_PASSWORD:
    external: true
  DB_USER:
    external: true
  DB_NAME:
    external: true
